### ISSUE TITLE
incrementProgress() not works

### ISSUE THREAD

**Issue by daichiro** [mokumoku/SwiftWebViewProgress#1]
SwiftWebViewProgress:46
When this function calls, app crashes.
error: `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`

**Comment by winkelsdorf** [comment]
Probably because you changed a multiplication to a division?

Original Code from njk in ObjC:

``` objc
- (void)incrementProgress
{
    float progress = self.progress;
    float maxProgress = _interactive ? NJKFinalProgressValue : NJKInteractiveProgressValue;
    float remainPercent = (float)_loadingCount / (float)_maxLoadCount;
    float increment = (maxProgress - progress) * remainPercent;
    progress += increment;
    progress = fmin(progress, maxProgress);
    [self setProgress:progress];
}
```

Your code:

``` swift
private func incrementProgress() {
    var progress = self.progress
    var maxProgress = interactive == true ? FinalProgressValue : InteractiveProgressValue

    let remainPercent = Float(loadingCount / maxLoadCount)
    let increment = (maxProgress - progress) / remainPercent // Here we go.. ;)
    progress += increment
    progress = fmin(progress, maxProgress)
    setProgress(progress)
}
```

Anyway great work, thank you for taking care of the swift conversion!

Cheers

**Comment by daichiro** [comment]
Oops! Thank you for helping!
I will try it :+1:

**Comment by daichiro** [comment]
I found.
The result of zero divide is different in Int and Float.

```
let a: Int = 0
let b: Int = 0
a / b       // EXC_BAD_INSTRUCTION

let c: Float = 0
let d: Float = 0
c / d       // NaN but Not caused runtime error
```

**Comment by daichiro** [comment]
https://github.com/mokumoku/SwiftWebViewProgress/blob/master/SwiftWebViewProgress/SwiftWebViewProgress/SwiftWebViewProgress.swift#L50
This code is `Int / Int` so caused runtime error

**Comment by daichiro** [comment]
also, I missed a multiplication to a division.

**Comment by winkelsdorf** [comment]
Glad I could help! Looks good to me, I'll test it in a moment.

Yes, that NaN is a known caveat, feels veeeery uncommon if you are developing in other programming languages too.
