### ISSUE TITLE
Fix crashed at SwiftWebViewProgress.swift line 96.

### ISSUE THREAD

**Issue by bizhara** [mokumoku/SwiftWebViewProgress#10]
It need to change SwiftWebViewProgress.swift line 96 to `isFragmentJump = nonFragmentURL == request.url?.absoluteString` or always crashed.
Fix please!

**Comment by daichiro** [comment]
Hi, @bizhara
I'm sorry for delay response.
 
Now, I fixed it by #12 and released version 0.3!
Thanks! 👍
