### ISSUE TITLE
Plz update to Swift3 ,tks

### ISSUE THREAD

**Issue by jsjjkfc** [mokumoku/SwiftWebViewProgress#7]

**Comment by daichiro** [comment]
Hi @jsjjkfc ,
I will update in this weekend, so please wait
or please pull request :)

**Comment by daichiro** [comment]
**UPDATED**
Now we can use this on Xcode8 / Swift 3.0 ! (see: #8 )
so please update your `Podfile` like this

```
pod 'SwiftWebViewProgress', '~> 0.2'
```

...and run `pod update`
